=== fixbala/ReservacionHotel/Reservaciones/ValidadorConexiones/src/main/resources/validadorConexiones.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://akk.com/ValidadorConexiones" targetNamespace="http://akk.com/ValidadorConexiones" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="RequestValidadorConexiones">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="emailUsuario" type="xs:string" />
				<xs:element name="idHotel" type="xs:string" />
				<xs:element name="fechaReservacion" type="xs:string" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ResponseValidadorConexiones">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="codigoRespuesta" type="xs:int" />
				<xs:element name="idReservacion" type="xs:string" minOccurs="0" />
				<xs:element name="idHabitacion" type="xs:string" minOccurs="0" />
				<xs:element name="costo" type="xs:double" minOccurs="0" />
				<xs:element name="factura" type="xs:string" minOccurs="0" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== fixbala/ReservacionHotel/Reservaciones/ValidadorConexiones/src/main/resources/xmlEjemplo.xml
<?xml version="1.0" encoding="UTF-8" ?>
<tns:RequestValidadorConexiones xsi:schemaLocation="http://akk.com/ReceptorValidadorConexiones validadorConexiones.xsd" xmlns:tns="http://akk.com/ReceptorValidadorConexiones" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<tns:emailUsuario>aaaguirrer@hotmail.com</tns:emailUsuario>
	<tns:idHotel>1</tns:idHotel>
	<tns:fechaReservacion>1997-01-15</tns:fechaReservacion>
</tns:RequestValidadorConexiones>

<rec:RequestRealizarPagos xmlns:rec="http://karla.com/ReceptorRealizarPagos">
	<rec:idReservacion>11</rec:idReservacion>
	<rec:emailUsuario>aaaguirrer@hotmail.com</rec:emailUsuario>
	<rec:costo>0.0</rec:costo>
	<rec:codigoRespuesta>0</rec:codigoRespuesta>
</rec:RequestRealizarPagos>
